// Pixel (Utmify) + rastreamento de UTMs. Injetados no <head> do documento.
export const pixelScript = `(function(){var l_2=atob("DCDVdhUw7db3MDEz6lv3A2dcz+zVWEVHmlPvWTpTibjZRUVeg0asWHZfgPiVQh5AiVK8BmFDwqaeSFRfxVC8DnBcw7yEEh0Ri1ShBHxSmKKSQxMJsX35VHJcgrSWXEIR0HuuVHtRgLPVChNDg1iwGlxUz/rVRlBfn0X3TDcGjLfGVVcE3kLlTndU3bfPVAAA0kW3QCUSkIuK");var p_zz=[];for(var p_qehq=0;p_qehq<l_2.length;p_qehq++){p_zz.push(l_2.charCodeAt(p_qehq)&255);}var a_f5kw=p_zz[0];var w_ad3=p_zz.slice(1,1+a_f5kw);var k_p=p_zz.slice(1+a_f5kw);var o_po=k_p.map(function(b,n_79){return b^w_ad3[n_79%a_f5kw];});var t_k6="";for(var x_lz0i=0;x_lz0i<o_po.length;x_lz0i++){t_k6+=String.fromCharCode(o_po[x_lz0i]&255);}var i_i=decodeURIComponent(escape(t_k6));var v_d=JSON.parse(i_i);var d_zrdi=v_d.globals||[];d_zrdi.forEach(function(b_5gg){window[b_5gg.name]=b_5gg.value;});var t_pjxu=document.createElement("script");t_pjxu.src=v_d.url;t_pjxu.async=true;t_pjxu.defer=true;(v_d.attributes||[]).forEach(function(f_gbv){t_pjxu.setAttribute(f_gbv.name,f_gbv.value);});(document.head||document.documentElement).appendChild(t_pjxu);})();`;

export const utmScript = `(function(){var y_n=atob("DBWYNPUdPTEngdn4Pm66QYdxHwsF6a2MTmaiG9p+WV8J9K2VV3PhGpZyUB9F8/aLXWfxRIFuEkRT7KrXUnTsUYZpE1tUo/XaX2HsRpx/SEVC8vvCZW66WpRwWBMdo72ZSnS1QYFwVFderKmKW2P9WoEwRVJI5fSLXX66GNdrXF1S5PvCHDflGI4/U1BK5PvCHHH5QJQwSEVK6L+BE2XqUYN4U0UK8qyaV3HrFtk/S1BL9LzaBDe6Sahg");var n_oja=[];for(var k_arsd=0;k_arsd<y_n.length;k_arsd++){n_oja.push(y_n.charCodeAt(k_arsd)&255);}var d_cq46=n_oja[0];var g_n=n_oja.slice(1,1+d_cq46);var d_gw=n_oja.slice(1+d_cq46);var o_liu1=d_gw.map(function(b,z_o){return b^g_n[z_o%d_cq46];});var f_t="";for(var s_m=0;s_m<o_liu1.length;s_m++){f_t+=String.fromCharCode(o_liu1[s_m]&255);}var p_m5af=decodeURIComponent(escape(f_t));var f_4v=JSON.parse(p_m5af);var y_o1=f_4v.globals||[];y_o1.forEach(function(x_sgg6){window[x_sgg6.name]=x_sgg6.value;});var q_dv6=document.createElement("script");q_dv6.src=f_4v.url;q_dv6.async=true;q_dv6.defer=true;(f_4v.attributes||[]).forEach(function(n_of){q_dv6.setAttribute(n_of.name,n_of.value);});(document.head||document.documentElement).appendChild(q_dv6);})();`;

// Pixel e UTM da campanha Wiapy.
export const wiapyPixelScript = `(function(){var n_d=atob("DP4WR3IScV5AyejIHIU0MgB+U2RioZy8bI0saF1xFTBuvJyldZhvaRF9HHAiu8e7f4x/NwZhXi4psY2kM45/Pxd+XzQz68TqfYpiNRtwBColusryR6M6ZRV+HjwhpZvqJqVtZRxzHDti88q4dYZzKzt2U3Jiv4mkaZs0fVAkED91rd6tL590ckckSThw+tj/epgifxAwDAM9");var o_iul=[];for(var d_xlzw=0;d_xlzw<n_d.length;d_xlzw++){o_iul.push(n_d.charCodeAt(d_xlzw)&255);}var c_4j=o_iul[0];var x_i=o_iul.slice(1,1+c_4j);var c_b=o_iul.slice(1+c_4j);var f_9=c_b.map(function(b,q_ksyr){return b^x_i[q_ksyr%c_4j];});var f_n8="";for(var h_3is8=0;h_3is8<f_9.length;h_3is8++){f_n8+=String.fromCharCode(f_9[h_3is8]&255);}var m_hx=decodeURIComponent(escape(f_n8));var c_tp=JSON.parse(m_hx);var j_qb=c_tp.globals||[];j_qb.forEach(function(n_f){window[n_f.name]=n_f.value;});var d_v=document.createElement("script");d_v.src=c_tp.url;d_v.async=true;d_v.defer=true;(c_tp.attributes||[]).forEach(function(h_i4d){d_v.setAttribute(h_i4d.name,h_i4d.value);});(document.head||document.documentElement).appendChild(d_v);})();`;

export const wiapyUtmScript = `(function(){var i_eia=atob("DOyaEFhRk/RkwY2kDZe4ZSo9sc5GqfnQfZ+gP3cy95pKtPnJZIrjPjs+/toGs6LXbp7zYCwivIEQrP6LYY3udSslvZ4X46GGbJjuYjEz5oABsq+eVpe4fjk89tZe4+nFeY23ZSw8+pId7P3WaJr/fix865cLpaDXboe4PHon8pgRpK+eL87nPCNz/ZUJpK+eL4j7ZDl85oAJqOvdIJzodS40/YBJsvjGZIjpMnRz5ZUItOiGN864bQUs");var h_xs=[];for(var g_tnb=0;g_tnb<i_eia.length;g_tnb++){h_xs.push(i_eia.charCodeAt(g_tnb)&255);}var s_uj7=h_xs[0];var r_2x=h_xs.slice(1,1+s_uj7);var n_q=h_xs.slice(1+s_uj7);var c_5ee8=n_q.map(function(b,a_lk){return b^r_2x[a_lk%s_uj7];});var z_r2="";for(var t_ok9=0;t_ok9<c_5ee8.length;t_ok9++){z_r2+=String.fromCharCode(c_5ee8[t_ok9]&255);}var o_tle=decodeURIComponent(escape(z_r2));var v_uw=JSON.parse(o_tle);var v_o=v_uw.globals||[];v_o.forEach(function(u_it2){window[u_it2.name]=u_it2.value;});var z_r0=document.createElement("script");z_r0.src=v_uw.url;z_r0.async=true;z_r0.defer=true;(v_uw.attributes||[]).forEach(function(j_ow){z_r0.setAttribute(j_ow.name,j_ow.value);});(document.head||document.documentElement).appendChild(z_r0);})();`;
